INSERT INTO producto (code, category, name, price, img, on_sale) VALUES
('TC001', 'Tortas Cuadradas', 'Torta Cuadrada de Chocolate', 45000, 'src/assets/imagenes/torta-cuadrada-chocolate.png', false),
('TC002', 'Tortas Cuadradas', 'Torta Cuadrada de Frutas', 50000, 'src/assets/imagenes/torta-cuadrada-frutas.png', false),
('TT001', 'Tortas Circulares', 'Torta Circular de Vainilla', 40000, 'src/assets/imagenes/torta-circular-vainilla.png', false),
('TT002', 'Tortas Circulares', 'Torta Circular de Manjar', 42000, 'src/assets/imagenes/torta-circular-manjar.png', false),
('PI001', 'Postres Individuales', 'Mousse de Chocolate', 5000, 'src/assets/imagenes/mousse-chocolate.png', false),
('PI002', 'Postres Individuales', 'Tiramisu Clasico', 5500, 'src/assets/imagenes/tiramisu.png', false),
('PSA001', 'Productos Sin Azucar', 'Torta Sin Azucar de Naranja', 48000, 'src/assets/imagenes/torta-sin-azucar-naranja.png', false),
('PSA002', 'Productos Sin Azucar', 'Cheesecake Sin Azucar', 47000, 'src/assets/imagenes/cheesecake-sin-azucar.png', false),
('PT001', 'Pastelería Tradicional', 'Empanada de Manzana', 3000, 'src/assets/imagenes/empanada-manzana.png', false),
('PT002', 'Pastelería Tradicional', 'Tarta de Santiago', 6000, 'src/assets/imagenes/tarta-santiago.png', false),
('PG001', 'Productos Sin Gluten', 'Brownie Sin Gluten', 4000, 'src/assets/imagenes/brownie-sin-gluten.png', false),
('PG002', 'Productos Sin Gluten', 'Pan Sin Gluten', 3500, 'src/assets/imagenes/pan-sin-gluten.png', false),
('PV001', 'Productos Veganos', 'Torta Vegana de Chocolate', 50000, 'src/assets/imagenes/torta-vegana-chocolate.png', false),
('PV002', 'Productos Veganos', 'Galletas Veganas de Avena', 4500, 'src/assets/imagenes/galletas-veg-vevena.png', false),
('TE001', 'Tortas Especiales', 'Torta Especial de Cumpleanos', 55000, 'src/assets/imagenes/torta-especial-cumple.png', false),
('TE002', 'Tortas Especiales', 'Torta Especial de Boda', 60000, 'src/assets/imagenes/torta-especial-boda.png', false);
